# Generated by Django 5.0.6 on 2025-05-12 06:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Household', '0003_illegaldumping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='illegaldumping',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='illegaldumping',
            name='report_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
